### ISSUE TITLE
FALM throws exception on en_us.xml and zh_tw.xml

### ISSUE THREAD

**Issue by JohnBergman** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#19]
ALM is throwing these exceptions, note, us.xml and tw.xml appear to be enus.xml and zhtw.xml; which are, in fact present.
System.IO.FileNotFoundException: Could not find file 'xxxxxxxx\umbraco\config\lang\us.xml'.
File name: 'xxxxxxxx\umbraco\config\lang\us.xml'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.OpenUrlDelegate(Object xmlResolver)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.CompressedStack.Run(CompressedStack compressedStack, ContextCallback callback, Object state)
   at System.Xml.XmlTextReaderImpl.OpenUrl()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at Umbraco.Core.XmlHelper.OpenAsXmlDocument(String filePath)
   at FALM.Housekeeping.Helper.HKLanguageInstaller.UpdateActionsForLanguageFile(String languageFile, String area, String key, String value)
   at FALM.Housekeeping.Helper.HKLanguageInstaller.InstallLanguageKey(String area, String key, String value)
 2017-08-04 15:31:38,283 [P49344/D2/T1] ERROR FALM.Housekeeping.Helper.HKLanguageInstaller - NewPackage Error in language installer
System.IO.FileNotFoundException: Could not find file 'xxxxxxxxxxx\umbraco\config\lang\tw.xml'

**Comment by afabri73** [comment]
Hi John,
yesterday I've update FALM package that should fix this problem.
Try to install the new package and tell me if the problem is fixed.

I now tried with this languages and I have no exception:
Italian, English (US), English (GB), Japan, Chinese, Korean

I look forward to your reply
Adriano

**Comment by JohnBergman** [comment]
Have you prepared a build for us to try?

**Comment by afabri73** [comment]
Sure,
you can download the update package in [FALM Housekeeping project page](https://our.umbraco.org/projects/backoffice-extensions/falm-housekeeping) on our.umbraco.org.

**Comment by JohnBergman** [comment]
This appears to be fixed.

**Comment by afabri73** [comment]
Great!!! :-)
